# Generated by Django 3.0 on 2019-12-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_team_home', models.IntegerField()),
                ('score_team_away', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('games_played', models.IntegerField()),
                ('games_won', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_played', models.IntegerField(default=0)),
                ('three_pointers_made', models.IntegerField(default=0)),
                ('three_pointers_attempted', models.IntegerField(default=0)),
                ('two_pointers_made', models.IntegerField(default=0)),
                ('two_pointers_attempted', models.IntegerField(default=0)),
                ('free_throws_made', models.IntegerField(default=0)),
                ('free_throws_attempted', models.IntegerField(default=0)),
                ('off_rebounds', models.IntegerField(default=0)),
                ('def_rebounds', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('personal_fouls', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball_game_app.Games')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketball_game_app.Players')),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basketball_game_app.Teams'),
        ),
        migrations.AddField(
            model_name='games',
            name='team_away',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_games', to='basketball_game_app.Teams'),
        ),
        migrations.AddField(
            model_name='games',
            name='team_home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_games', to='basketball_game_app.Teams'),
        ),
    ]
