# Generated by Django 3.0 on 2019-12-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='games',
            constraint=models.UniqueConstraint(fields=('team_home', 'team_away'), name='unique_teams'),
        ),
    ]
