# Generated by Django 3.0 on 2019-12-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_game_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_team_home', models.IntegerField()),
                ('score_team_away', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='games',
            name='score_team_away',
        ),
        migrations.RemoveField(
            model_name='games',
            name='score_team_home',
        ),
        migrations.AlterField(
            model_name='teams',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teams',
            name='games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_team_home', models.IntegerField()),
                ('score_team_away', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball_game_app.Games')),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='q1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='first_q', to='basketball_game_app.Quarter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='q2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='second_q', to='basketball_game_app.Quarter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='q3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='third_q', to='basketball_game_app.Quarter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='q4',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_q', to='basketball_game_app.Quarter'),
            preserve_default=False,
        ),
    ]
