# Generated by Django 3.0 on 2019-12-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_game_app', '0002_auto_20191209_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='conference',
            field=models.IntegerField(choices=[(0, 'EAST'), (1, 'WEST')], default=None),
            preserve_default=False,
        ),
    ]
