# Generated by Django 3.0 on 2019-12-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_game_app', '0002_auto_20191210_1230'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='games',
            name='unique_teams',
        ),
        migrations.AlterUniqueTogether(
            name='games',
            unique_together={('team_home', 'team_away')},
        ),
    ]
