# Generated by Django 3.0 on 2019-12-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_game_app', '0003_teams_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='teams',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='basketball_game_app.Group'),
        ),
    ]
