# Generated by Django 3.0 on 2019-12-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_game_app', '0003_auto_20191210_1232'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='games',
            unique_together=set(),
        ),
    ]
