# Generated by Django 3.0 on 2019-12-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_game_app', '0004_auto_20191210_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='team_away_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='team_home_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
