# Generated by Django 3.0 on 2019-12-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_game_app', '0005_auto_20191211_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='team_away_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='team_home_score',
            field=models.IntegerField(null=True),
        ),
    ]
