# Generated by Django 3.0 on 2019-12-11 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_game_app', '0006_auto_20191211_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='TeamStats',
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='minutes_played',
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='player',
        ),
        migrations.AddField(
            model_name='teamstats',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketball_game_app.Teams'),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='technical_fouls',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('three_pointers_made', models.IntegerField(default=0)),
                ('three_pointers_attempted', models.IntegerField(default=0)),
                ('two_pointers_made', models.IntegerField(default=0)),
                ('two_pointers_attempted', models.IntegerField(default=0)),
                ('free_throws_made', models.IntegerField(default=0)),
                ('free_throws_attempted', models.IntegerField(default=0)),
                ('off_rebounds', models.IntegerField(default=0)),
                ('def_rebounds', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('personal_fouls', models.IntegerField(default=0)),
                ('technical_fouls', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball_game_app.Games')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketball_game_app.Players')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
