# Generated by Django 3.0 on 2020-01-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_game_app', '0007_auto_20191211_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketball_game_app.Teams'),
        ),
    ]
